---
abstract: 'Kestrel Client for Perl'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Kestrel
requires:
  IO::Socket: 0
  JSON::Any: 0
  JSON::XS: 0
  Moose: 0
resources:
  repository: https://github.com/gphat/net-kestreol
version: 0.02
