---
abstract: 'Kestrel Client for Perl'
author:
  - 'Cory G Watson <gphat@cpan.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  strict: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Kestrel
requires:
  IO::Socket: 0
  Moose: 0
resources:
  homepage: https://github.com/gphat/net-kestrel
  repository: https://github.com/gphat/net-kestrel.git
version: 0.08
